#!/bin/bash

#
# Constants -------------------------------------------------------------
#

version=0.2
ledredpin=17
ledgreenpin=27
ledyellowpin=22
logfile=/var/log/archtester.log
cmdlogfile=/var/log/archtester.cmd.log
cmderrlogfile=/var/log/archtester.cmderr.log

#
# Initialize ------------------------------------------------------------
#

daemon=1
debug=1
sleeptime=2
blinhalftime=0.3

touch $logfile
date >> $logfile
echo "Started" >> $logfile
sync

#
# Function definitions --------------------------------------------------
#

#
# Kill the archtester process
#

function archtester_kill {
  archtester_ledsmode off
  killall archtester > /dev/null 2> /dev/null
}

#
# Debug printouts
#

function archtester_debug {
    if [ $debug = 1 ]
    then
	echo "archtester: debug: $*"
    fi
}

#
# Initialize leds
#

function archtester_ledinit {
  gpio -g mode $ledredpin out
  gpio -g mode $ledgreenpin out
  gpio -g mode $ledyellowpin out
}

#
# Blink a led
#
# Input: pin number (gpw numbering)
#

function archtester_ledblink {
    pin=$1
    sleeptimearg=$2
    sleeptimeargm=`(echo scale=0; echo "$sleeptimearg * 100") | bc | cut -f1 -d.`
    archtester_debug "Sleeptime $sleeptimearg, sleeptimem $sleeptimeargm"
    tused=0
    tusedm=0
    while [ $tusedm -lt $sleeptimeargm ]
    do
        gpio -g write $pin 1
    	sleep $blinkhalftime
        gpio -g write $pin 0
    	sleep $blinkhalftime
	tused=`(echo scale=4; echo $tused + $blinkhalftime + $blinkhalftime) | bc`
 	tusedm=`(echo scale=0; echo "$tused * 100") | bc | cut -f1 -d.`
 	archtester_debug "Tused $tused, tusedm $tusedm"
    done
}

#
# Set one led mode
#
# Input: pin number (gpw numbering), state (on, off, blink), sleeptime (seconds)
#

function archtester_ledset {
    pinni=$1
    state=$2
    sleeparg=$3
    case $state in
	off)
	    gpio -g write $pinni 0;;
	on)
	    gpio -g write $pinni 1;;
	blink)
	    archtester_ledblink $pinni $sleeparg &
	    nop=nop;;
	*) nop=nop;;
    esac
}

#
# Set the led bank mode
#
# Input: mode (off, flash, search, good, bad), sleeptime (seconds)
#

function archtester_ledsmode {
	
    redstate=off
    greenstate=off
    yellowstate=off
    
    # killall gpio > /dev/null 2> /dev/null
    
    case $1 in
	off)
	    redstate=off
	    greenstate=off
	    yellowstate=off;;
	flash)
	    redstate=on
	    greenstate=on
	    yellowstate=on;;
	search)
	    redstate=off
	    greenstate=off
	    yellowstate=blink;;
	good)
	    redstate=off
	    greenstate=on
	    yellowstate=off;;
	bad)
	    redstate=on
	    greenstate=off
	    yellowstate=off;;
	*)
	    redstate=blinking
	    greenstate=blinking
	    yellowstate=blinking;;
    esac
    
    archtester_ledset $ledredpin $redstate
    archtester_ledset $ledgreenpin $greenstate
    archtester_ledset $ledyellowpin $yellowstate
}

#
# One round of analysis ------------------------------------------------------
#

function archtester_analyze {

    archtester_debug Looking at interfaces

    #
    # Initialize analysis
    #
    
    v4found=0
    v4publicfound=0
    v6found=0

    #
    # Determine what interfaces we have
    #
    
    interfaces=`ifconfig -s|fgrep -v Iface|fgrep -v lo|cut -f1 -d' '`
    
    #
    # Look at each interface, and what addresses it provides
    #
    
    for interface in $interfaces
    do
	
	ifconfig $interface > /tmp/interface.$interface.data
	cat /tmp/interface.$interface.data |
	    sed 's/inet /inet addr: /g' |
	    grep 'inet addr:' |
	    cut -f2 -d: |
	    sed 's/^ *//g' |
	    cut -f1 -d' ' > /tmp/interface.$interface.addrs.v4
	cat /tmp/interface.$interface.data |
	    sed 's/inet6 /inet6 addr: /g' |
	    grep 'inet6 addr:' |
	    cut -f2- -d: |
	    sed 's/^ *//g' |
	    cut -f1 -d' ' > /tmp/interface.$interface.addrs.v6
	cat /tmp/interface.$interface.data |
	    sed 's/inet6 /inet6 addr: /g' |
	    grep 'inet6 addr:' |
	    sed 's/scopeid *0x20.link./Scope: Link/g' |
	    sed 's/scopeid *0x0.global./Scope: Global/g' |
	    sed 's/scopeid *0x5/Scope: Link/g' |
	    sed 's/^ *//g' |
	    sed 's/^.*Scope://g' |
	    sed 's/^ *//g' |
	    cut -f1 -d' ' > /tmp/interface.$interface.scopes.v6
	
	#
	# Determine from the IPv4 addresses what kind of IPv4 connectivity we have
	#
	
	for a in `cat /tmp/interface.$interface.addrs.v4`
	do
	    case $a in
		10.*) v4found=1;;      # RFC 1981
		192.168.*) v4found=1;; # RFC 1981
		172.16.*) v4found=1;;  # RFC 1981
		169.254.*) ;;          # RFC 5731
		0.0.0.0) ;;            # avoid special case if not assigned
		127.*) ;;	             # avoid localhost addresses
		*.*.*.*) v4found=1;
			 v4publicfound=1;;
		*) ;;                  # anything else, in case data is garbled
	    esac
	done
	
	#
	# Determine from the IPv6 address scopes what kind of IPv6 connectivity we have
	
	for s in `cat /tmp/interface.$interface.scopes.v6`
	do
	    case $s in
		Global) v6found=1;;
		*) ;;
	    esac
	done
	
    done
    
    archtester_debug V4: $v4found
    archtester_debug V4 public address $v4publicfound
    archtester_debug V6: $v6found
    
}

#
# Analyzer main loop
#

function archtester_loop {

    #
    # Initialise tester
    #

    archtester_debug initialize
    archtester_ledinit
    archtester_ledsmode off 0.5
    sleep 0.5
    archtester_ledsmode flash 1.5
    sleep 1.5
    archtester_ledsmode off 0.5
    prevmode=none
    
    #
    # Main loop
    #
    
    archtester_debug main loop
    while true
    do
	
	archtester_analyze
	
	if [ $v4publicfound = 1 -o $v6found = 1 ]
	then
	    mode=good
	else
	    if [ $v4found = 0 ]
	    then
		mode=search
	    else
		mode=bad
	    fi
	fi
	archtester_ledsmode $mode $sleeptime
	archtester_debug "Analysis result = $mode"
	if [ $mode = $prevmode ]
	then
	    nop=nop
	else
	    date >> $logfile
	    echo mode=$mode v4=$v4found public=$v4publicfound v6=$v6found >> $logfile
	    prevmode=$mode
	fi
	sleep $sleeptime
	
    done
}

#
# Main program -----------------------------------------------------
#

#
# Parse arguments
#

while [ $# -gt 0 ]
do
    case x$1 in
	x-X)
	    shift
	    exec archtester_kill;;
	x-v)
	    shift
	    echo "archtester version " $version
	    exit 0;;
	x-f)
	    shift
	    daemon=0;;
	x-d)
	    shift
	    debug=1;;
	x-q)
	    shift
	    debug=0;;
	x-s)
	    shift
	    sleeptime=$1
	    shift
	    debug=0;;
	*)
	    echo "archtester: unexpected argument: $1"
	    exit 1;;
    esac
done

#
# Decide if to run as a daemon or not
#

if [ $daemon = 0 ]
then
    archtester_debug foreground
    archtester_loop
else
    archtester_debug daemon
    archtester_loop > $cmdlogfile 2> $cmderrlogfile &
    disown -r -h
    exit 0
fi
